#!/user/bin/python 3
Ramadi = '\033[1;30m'
A7mar = '\033[1;31m'
A5thar = '\033[1;32m'
Asfar = '\033[1;33m'
Azra9 = '\033[1;34m'
Roz = '\033[1;35m'
Azra92 = '\033[1;36m'
blue = '\033[34;1m'
green = '\033[32;1m'
purple = '\033[35;1m'
cyan = '\033[36;1m'
red = '\033[31;1m'
white = '\033[37;1m'
yellow = '\033[33;1m' 
b=('''echo "
            =========== #############################..
      +++++ +++++++++++ #         ALLOUI $$ DZ      #...
            =========== #-------------------------- #....
  +++++     +++++++++++ #         TOOL % DZ         #....
            =========== #---------------------------#....
      ++++  +++++++++++ #            v 1.0.0        #...
            =========== #___________________________#..
           ++++++++++++ #############################" |lolcat ''')

import os
import sys
import time
os.system("apt update && apt upgrade && clear")
os.system ('figlet "2018/2"|lolcat')
time.sleep(0.5)
os.system ('figlet "TOOL DZ"|lolcat')
time.sleep(0.5)
os.system ('figlet "update"|lolcat')
time.sleep(2)
os.system('clear')
os.system('clear')
os.system('clear')
print(A5thar)
print(A7mar)
os.system(b)
os.system('toilet -f mono12 "TOOL DZ "|lolcat')
os.system('echo "My Channel on Youtube:https://youtu.be/AR1KdxMeUHM" | lolcat -F 10')
def x():

    print(Asfar) 
    print('[1]==>fakecall    <========> [17]==>fb2')
    time.sleep(0.5)
    print('[2]==> SMS        <========> [18]==>tool-mux')
    time.sleep(0.5)
    print('[3]==>weeman      <========> [19]==>ipcs ')
    time.sleep(0.5)
    print('[4]==>sqlmap +    <========> [20]==>Ghost')
    time.sleep(0.5)
    print('[5]==>XSStrike    <========> [21]=>SCr-ZEro')
    time.sleep(0.5)
    print('[6]==>nmap        <========> [22]==>TermuxAlpine ')
    time.sleep(0.5)
    print('[7]==>jboos       <========> [23]==>TERMUX1')
    time.sleep(0.5)
    print('[8]==>soerce      <========> [24]==>SCr-framework ')
    time.sleep(0.5)
    print('[9]==>pixiewps    <========> [25]==>Bunch ')
    time.sleep(0.5)
    print('[10]==>arachni    <========> [26]==>M-map ')
    time.sleep(0.5)
    print('[11]==>cuup       <========> [27]==>metasploit-framework ')
    time.sleep(0.5)
    print('[12]==>setoolkit  <========> [28]==>Tmux-Bunch ')
    time.sleep(0.5)
    print('[13]==>ncrack     <========> [29]==>Matermuxx')
    time.sleep(0.5)
    print('[14]==>reaver     <========> [30]==>DZjecter')
    time.sleep(0.5)
    print('[15]==>ssls       <========> [31]==>Hasher')
    time.sleep(0.5)
    print('[16]==>bluepot    <========> [32]==>T-host')
    time.sleep(0.5)
    print('[99]==> exit      <========> [33]==>TOKET ')
    time.sleep(0.5)
    print('[34]==> mbf  +    <========> [35]==>osif + ')
    time.sleep(0.5)
    print('[36]==>LITEDDOS + <========> [37]==>FB-React +')
    time.sleep(0.5)
    print('[38]==>xl.py +    <========> [39]==>vbscan +')
    time.sleep(0.5)
    print('[40]==>kubik-bot +<========> [41]==>BAJINGANv6 +')
    time.sleep(0.5)
    print('[42]==> LITESPAM +<========> [54]==> BlackNmap +')
    time.sleep(0.5)
    print(Roz)
    os.system("echo '-------------------------------------------------' | lolcat -F 10")
    print('+++++++++++++++++++ALL-TOOL-TERMUX+++++++++++++++')
    os.system("echo '-------------------------------------------------' | lolcat")
    print(Asfar)
    print('[43]1-TOOLSINSTALLERv1 (46) tools +')
    time.sleep(0.5)
    print('[44]2-TOOLSINSTALLERv2 (101) tools +')
    time.sleep(0.5)
    print('[45]3-TOOLSINSTALLERv3 (311) tools +')                                                               
    time.sleep(0.5)
    print('[46]4-TOOLSINSTALLERv4 (401) tools +')                                                               
    time.sleep(0.5)
    print('[47]5-TOOLSv2 (52) tools +')                                                                
    time.sleep(0.5)
    print('[48]6-T00Ls-B4J1N64N (29) tools+')                                                               
    time.sleep(0.5)
    print('[49]7-T00Ls-B4J1N64N2 (41) tools+')                                                               
    time.sleep(0.5)
    print('[50]8-T00Ls-B4J1N64Nv3 (51) tools+')                                                               
    time.sleep(0.5)
    print('[51]9-B4J1N64Nv4 (80) tools +')                                                               
    time.sleep(0.5)
    print("[52]DarkFly (100) tools +")
    time.sleep(0.5)
    print(Roz)
    os.system ("echo '***************************************************' |lolcat")
    print("***      all  the basicvpursuits are in termux   ***")
    os.system("echo '***************************************************' | lolcat")
    time.sleep(0.5)
    os.system('echo "------------------------53--------------------" | lolcat')
    time.sleep(0.5)
    os.system("echo '[55]++++++++++++moon-buggy+++++++++++++ '|lolcat")
    time.sleep(0.5)
    os.system("echo '                     -----------                       ' | lolcat -F 10")
    os.system('echo "                     |99- exit |                       " | lolcat -F 10')
    os.system('echo "                     -----------                       " | lolcat -F 10 ')
    print (A7mar)
    a = (input("enter number>>>>>"))
    if   a == "1" :
        print(A7mar)
        print("fakecall")
        os.system("git clone https://github.com/siputra12/fakecall && pkg install php")
        os.system("clear && ls && clear && cd fakecall && clear && figlet fakecall && php call.php && clear") 
    elif a == "2":
        print("SMS")
        os.system("git clone https://github.com/p4kl0nc4t/Spammer-Grab")
        os.system(" apt update && apt upgrade && pkg install wget && pkg install hacktronian && pkg install curl && pip2 install -r requirements.txt && pkg install bash && cd Spammer-Grab && ./auto-install.sh ")
        os.system(" clear && cd Spammer-Grab && clear && figlet SMS && python2 spammer.py")
    elif a == "3":
        os.system("figlet  weeman")
        time.sleep(3)
        os.system("git clone https://github.com/samyoyo/weeman.git && cd weeman && python weeman.py") 
    elif a == "4":
        os.system ('clear')
        os.system ('figlet sqlmap')
        os.system ('apt update && apt upgrade')                                 
        os.system ('git clone https://github.com/sqlmapproject/sqlmap.git')
        os.chdir ('sqlmap')
        os.system ('chmod +x sqlmap.py && chmod +x sqlmapapi.py')
        os.system ('clear')
        print(blue),('jalankan dg perintah:')
        time.sleep (1.7)
        print(blue),('cd sqlmap')
        print(blue),('python2 sqlmap.py -u <web vuln>')
    elif a == "5":
        os.system('figlet XSStrike ')
        time.sleep(3)
        os.system("git clone https://github.com/UltimateHackers/XSStrike.git && cd XSStrike && pip install -r requirements.txt && clear && python xsstrike ")
    elif a == "6":
        os.system('figlet nmap')
        time.sleep(3)
        os.system("git clone https://github.com/nmap/nmap.git")
        os.system("cd nmap && ./configure && make && make install")
    elif a == "7":
        os.system('figlet  jboos')
        time.sleep(3)
        os.system("git clone https://github.com/SpiderLabs/jboss-autopwn.git")
    elif a == "8":
        os.system('figlet soerce site')
        time.sleep(3)
        import urllib.request
        url = input('site ====>>') 
        b  = urllib.request.urlopen(url)
        readh  = b.read()
        print (readh)
    elif a == "9":
        os.system("figlet pixiewps")
        time.sleep(3)
        os.system("git clone https://github.com/wiire/pixiewps.git")
        os.system("cd pixiewps & make ")
        os.system("sudo make install")
    elif a == "10":
        os.system("figlet arachni")
        time.sleep(3)
        os.system("git clone git://github.com/Arachni/arachni.git")
        os.system("cd arachni && sudo gem install bundler && bundle install --without prof && rake install")
    elif a == "11":
        os.system("figlet cupp")
        time.sleep(3)
        os.system("git clone https://github.com/Mebus/cupp.git")
        print("file downloaded successfully")
    elif a == "12":
        os.system("figlet setoolkit")
        time.sleep(3)
        os.system ("git clone https://github.com/trustedsec/social-engineer-toolkit.git")
        os.system("python social-engineer-toolkit/setup.py")
    elif a == "13":
        os.system("figlet ncrack")
        time.sleep(3)
        os.system("git clone https://github.com/sophsec/ruby-ncrack.git")
        os.system("cd ruby-ncrack")
        os.system("install ruby-ncrack")
    elif a == "14":
        os.system("figlet reaver")
        time.sleep(3)
        os.system("apt-get -y install build-essential libpcap-dev sqlite3 libsqlite3-dev aircrack-ng pixiewps")
        os.system("git clone https://github.com/t6x/reaver-wps-fork-t6x.git")
        os.system("cd reaver-wps-fork-t6x/src/ & ./configure")
        os.system("cd reaver-wps-fork-t6x/src/ & make")  
    elif a == "15":
        os.system("figlet  ssls")
        time.sleep(3)
        os.system("git clone https://github.com/moxie0/sslstrip.git")
        os.system("sudo apt-get install python-twisted-web")
        os.system("python sslstrip/setup.py")
    elif a == "16":
        os.system("figlet bluepot")
        time.sleep(3)
        os.system(" pkg install wget && wget https://github.com/andrewmichaelsmith/bluepot/raw/master/bin/bluepot-0.1.tar.gz && tar xfz bluepot-0.1.tar.gz && sudo java -jar bluepot/BluePot-0.1.jar")
    elif a == "17":
        os.system('figlet fb2')
        time.sleep(3)
        os.system("git clone https://github.com/Fakher01hacker/fb2")
    elif a == "18":
        os.system('figlet tool-mux')
        time.sleep(3)
        os.system("git clone https://github.com/Mehdi-boullouf/Tool-Mux")
    elif a == "19":
        os.system("figlet ipcs")
        time.sleep(3)
        os.system("git clone https://github.com/kancotdiq/ipcs")
    elif a == "20":
        os.system("figlet  Ghost")
        time.sleep(3)
        os.system("git clone https://github.com/islam928/Ghost")
    elif a == "21":
        os.system('figlet  SCr-ZEro')
        time.sleep(3)
        os.system('git clone https://github.com/Mehdi-boullouf/SCr-ZEro')
    elif a == "22":
        os.system("figlet TermuxAlpine")
        time.sleep(3)
        os.system("git clone https://github.com/Hax4us/TermuxAlpine")
        os.system("cd TermuxAlpine && ls")
    elif a == "23":
        os.system("figlet TERMUX1")
        time.sleep(3)
        os.system("pkg install python2 -y && git clone https://github.com/HusseinHajMohammed/Termux1 &&  cd Termux1 && chmod +x Termux1.py && python2 Termux1.py && cd Termux1 && python2 Termux1.py")
    elif a == "24":
        os.system('figlet SCr-framework')
        time.sleep(3)
        os.system("https://github.com/Mehdi-boullouf/SCr-framework && ls ")
    elif a == "25":
        os.system('figlet Bunch')
        time.sleep(3)
        os.system('https://github.com/Mehdi-boullouf/Bunch && ls')
    elif a == "26":
        os.system("figlet M-map")
        time.sleep(3)
        os.system("https://github.com/Mehdi-boullouf/M-map && ls")
    elif a == "27":
        os.system("figlet metasploit")
        time.sleep(3)
        os.system("pkg update && pkg upgrade && pkg install ruby  && pkg install curl && pkg install git && pkg install python2")
        os.system("curl -LO https://raw.githubusercontent.com/Hax4us/Metasploit_termux/master/metasploit.sh")
        os.system("ls && chmod +x metasploit.sh && bash metasploit.sh")
    elif a == "28":
        os.system("figlet Tmux-Bunch ")
        time.sleep(3)
        os.system("git clone https://github.com/Hax4us/Tmux-Bunch.git && ls")
    elif a == "29":
        os.system("figlet Matermuxx ")
        time.sleep(3)
        os.system("git clone https://github.com/Hider5/Matermuxx ")
    elif a == "30":
        os.system("figlet DZjecter  ")
        time.sleep(3)
        os.system("clear")
    elif a == "31":
        os.system("figlet Hasher ")
        time.sleep(3)
        os.system("git clone https://github.com/ciku370/hasher ")
    elif a == "32":
        os.system("figlet T-host ")
        time.sleep(3)
        os.system("git clone https://github.com/Bhai4You/T-Host")
    elif a == "33":
        os.system("figlet TOKET ")
        time.sleep(3)
        os.system("git clone https://github.com/Ranginang67/TOKET.git")
    elif a == "34":
        os.system ('clear')
        os.system ('figlet "mbf"')
        os.system ('apt update && apt upgrade')
        os.system ('pkg install python2')
        os.system ('pip2 install mechanize')
        os.system ('pip2 install --upgrade pip')
        os.system ('git clone https://github.com/YukersCreew/mbf')
        os.chdir ('mbf')
        os.system ('clear')
        os.system ('python2 MBF.py')
    elif a == "35":
        os.system ('clear')
        os.system ('figlet osif')
        os.system ('apt update && apt upgrade')
        os.system ('pip2 install --upgrade pip')
        os.system ('pip2 install requests mechanize')
        os.system ('git clone https://github.com/CiKu370/OSIF')
        os.chdir ('OSIF')
        os.system ('pip2 install -r requirements.txt')
        os.system ('clear')
        print(red),('ketik token (untuk login fb)')
        time.sleep(1.0)
        print(red),('ketik help (untuk melihat bantuan)')
        time.sleep(1.5)
        os.system ('python2 osif.py')
    elif a == "36":
        os.system ('clear')
        os.system ('figlet LITEDDOS')
        os.system ('apt update && apt upgrade')
        os.system ('pkg install python2')
        os.system ('git clone https://github.com/4L13199/LITEDDOS')
        os.chdir ('LITEDDOS')
        os.system ('clear')
        print (yellow)
        print ("Jalankan dg ketik perintah:")
        time.sleep(2.0)
        print ("$ cd LITEDDOS")
        time.sleep(2.0)
        print ("$ python2 LITEDDOS.py <ip> <port> <packet>")
    elif a == "37":
        os.system ('clear')
        os.system ('figlet FB-React')
        os.system ('apt update && apt upgrade')
        os.system ('apt install php curl -y')
        os.system ('git clone http://github.com/AMVengeance/FB-React.git')
        os.chdir (' FB-React')
        os.system ('chmod +x start')
        os.system ('clear')
        os.system ('./start')
    elif a == "38":
        os.system ('clear')
        os.system ('figlet xl.py')
        os.system ('apt update && apt upgrade')
        os.system ('git clone https://github.com/anggialberto/xl-py')
        os.chdir ('xl-py')
        os.system ('pip install --upgrade pip')
        os.system ('pip install -r requirements.txt')
        os.system ('chmod +x app.py')
        os.system ('clear')
        os.system ('python2 app.py')
    elif a == "54":
        os.system ('clear')
        os.system ('figlet BlackNmap')
        os.system ('apt update && apt upgrade')
        os.system ('git clone https://github.com/Xi4u7/BlackNmap')
        os.chdir ('BlackNmap')                                                                    
        os.system ('chmod +x blacknmap')
        os.system ('chmod 777 blacknmap')                                                         
        os.system ('clear')
        os.system ('sh blacknmap')
    elif a == "39":
        os.system ('clear')
        os.system ('figlet "BYE"')
        os.system ('apt update && apt upgrade -y')
        os.system ('apt install perl')
        os.system ('git clone https://github.com/rezasp/vbscan')
        os.chdir ('vbscan')
        os.system ('ls')
        os.system ('clear')
    elif a == "40":
        os.system ('clear')
        os.system ('figlet kubik-bot')
        os.system ('apt update && apt upgrade')
        os.system ('pkg install php')
        os.system ('git clone https://github.com/radenvodka/kubik-bot')
        os.chdir ('kubik-bot')
        os.system ('pkg install nano')
        os.system ('nano kubik.php')
        os.system('perl vbscan.pl')
    elif a == "41":
        os.system ('clear')
        os.system ('figlet BAJINGANv6')                                                                            
        os.system ('apt uodate && apt upgrade')                                                               
        os.system ('pip install --upgrade pip')
        os.system ('pip2 install termcolor')
        os.system ('pip2 install lolcat')                                                                     
        os.system ('apt install toilet')
        os.system ('git clone https://github.com/DarknessCyberTeam/BAJINGANv6')
        os.chdir ('BAJINGANv6')
        os.system ('clear')
        print(green),('inget!')
        print(red),('Username: BAJINGAN')
        print(red),('Password: Gans')
        time.sleep (5.5)
        os.system ('sh BAJINGAN.sh')
    elif a == "42":
        os.system ('clear')
        os.system ('figlet LITESPAM')
        os.system ('pkg update && pkg upgrade')
        os.system ('pkg install php')
        os.system ('pkg install toilet')
        os.system ('git clone https://github.com/4L13199/LITESPAM')
        os.chdir ('LITESPAM')
        os.system ('clear')
        os.system ('sh LITESPAM.sh')
    elif a == "43":
        try:
            os.chdir ("TOOLSINSTALLERv1")
            os.system ("sh Tuanb4dut.sh")
        except:
            os.system ('figlet "TOOL TERMUX"|lolcat')
            os.system ("apt update && apt upgrade")
            os.system ("pip2 install lolcat")
            os.system ("pkg install figlet")
            os.system ("pkg install php")
            os.system ("git clone https://github.com/TUANB4DUT/TOOLSINSTALLERv1")
            os.chdir ("TOOLSINSTALLERv1")
            os.system ("chmod +x Tuanb4dut.sh")
            os.system ("sh Tuanb4dut.sh")
    elif a == "44":
        try:
            os.chdir ("TOOLSINSTALLERv2")
            os.system ("sh Tuanb4dut.sh")
        except:
            os.system ('figlet "TOOL TERMUX"|lolcat')
            os.system ("apt update && apt upgrade")
            os.system ("pip2 install lolcat")
            os.system ("pkg install figlet")
            os.system ("pkg install php")
            os.system ("git clone https://github.com/TUANB4DUT/TOOLSINSTALLERv2")
            os.chdir ("TOOLSINSTALLERv2")
            os.system ("chmod +x Tuanb4dut.sh")
            os.system ("sh Tuanb4dut.sh") 
    elif a == "45":
        try:
            os.chdir ("TOOLSINSTALLERv3")
            os.system ("sh TUANB4DUT.sh")
        except:
            os.system ('figlet "TERMUX TOOL"|lolcat')
            os.system ("apt update && apt upgrade")
            os.system ("pkg install python python2 vim figlet curl")
            os.system ("pkg install php")
            os.system ("pip2 install lolcat")
            os.system ("https://github.com/TUANB4DUT/TOOLSINSTALLERv3")
            os.chdir ("TOOLSINSTALLERv3")
            os.system ("chmod +x TUANB4DUT.sh")
            os.system ("sh TUANB4DUT.sh")
    elif a == "46":
        try:
            os.chdir ("TOOLSINSTALLERv4")
            os.system ("sh TUANB4DUT.sh")
        except:                                                                                       
            os.system ('figlet "TOOL TERMUX"|lolcat')
            os.system ("apt update && apt upgrade")
            os.system ("pkg install python python2 vim figlet curl")
            os.system ("pkg install php")
            os.system ("pip2 install lolcat")
            os.system ("git clone https://github.com/TUANB4DUT/TOOLSINSTALLERv4")                     
            os.chdir ("TOOLSINSTALLERv4")
            os.system ("chmod 777 TUANB4DUT.sh")
            os.system ("sh TUANB4DUT.sh")
    elif a == "47":
        try:
            os.chdir ("TOOLSv2")
            os.system ("sh TU4NN1CKN4M3.sh")
        except:
            os.system ('figlet "TOOL TERMUX"|lolcat')
            os.system ("apt update && apt upgrade")
            os.system ("pkg install python python2 vim figlet url")
            os.system ("pip2 install lolcat")
            os.system ("pkg install git")
            os.system ("git clone https://github.com/TU4NN1CKN4M3/TOOLSv2")
            os.chdir ("TOOLSv2")
            os.system ("sh TU4NN1CKN4M3.sh")
    elif a == "48":
        try:
            os.chdir ("T00Ls-B4J1N64N")
            os.system ("./B4J1N64N")
        except:
            os.system ('figlet "Tool termux"|lolcat')
            os.system ("apt update && apt upgrade")
            os.system ("pkg install figlet toilet")
            os.system ("git clone https://github.com/DarknessCyberTeam/T00Ls-B4J1N64N")
            os.chdir ("T00Ls-B4J1N64N")
            os.system ("chmod 777 B4J1N64N")
            os.system ("./B4J1N64N")
    elif a == "49":
        try:
            os.chdir ("T00Ls-B4J1N64N2")
            os.system ("sh B4J1N64N.sh")
        except:
            os.system ('figlet "TERMUX TOOL"|lolcat')
            os.system ("apt update && apt upgrade")
            os.system ("pkg install figlet toilet")
            os.system ("git clone https://github.com/DarknessCyberTeam/T00Ls-B4J1N64N2")
            os.chdir ("T00Ls-B4J1N64N2")
            os.system ("chmod 777 B4J1N64N.sh")
            os.system ("sh B4J1N64N.sh")
    elif a == "50":
        try:
            os.chdir ("T00Ls-B4J1N64Nv3")
            os.system ("sh B4J1N64N.sh")
        except:
            os.system ('figlet "TERMUX TOOL"|lolcat')
            os.system ("apt update && apt upgrade")
            os.system ("pkg install figlet toilet")
            os.system ("git clone https://github.com/DarknessCyberTeam/T00Ls-B4J1N64Nv3")
            os.chdir ("T00Ls-B4J1N64Nv3")
            os.system ("chmod 777 B4J1N64N.sh")
            os.system ("sh B4J1N64N.sh")
    elif a == "51":
        try:
            os.chdir ("B4J1N64Nv4")
            os.system ("sh bajingan.sh")
        except:
            os.system ('figlet "TOOL TERMUX"|lolcat')
            os.system ("apt update && apt upgrade")
            os.system ("pkg install figlet toilet")
            os.system ("git clone https://github.com/DarknessCyberTeam/B4J1N64Nv4")
            os.chdir ("B4J1N64Nv4")
            os.system ("chmod 777 bajingan.sh")
            os.system ("sh bajingan.sh")
    elif a == "52":
        try:
            os.chdir ("DarkFly-Tool")
            os.system ("DarkFly")
        except:
            os.system ('figlet "TOOL TERMUX"|lolcat')
            os.system ("pkg install python2")
            os.system ("pkg install php")
            os.system ("git clone https://github.com/Ranginang67/DarkFly-Tool")
            os.chdir ("DarkFly-Tool")
            os.system ("chmod +x install.py")
            os.system ("python2 install.py")
            os.system ("DarkFly")
    elif a == "53":
        os.system('figlet "DON..."|lolcat')
        time.sleep(3)
        print(Azra9)
        print("Please, please +")
        time.sleep(0.5)
        os.system("clear")
        print("Please, please -")
        time.sleep(0.5)
        os.system("clear")
        print("Please, please +")
        time.sleep(0.5)
        os.system("clear")
        print("Please, please -")
        time.sleep(0.5)
        os.system("clear")
        print("Please, please +")
        time.sleep(0.5)
        os.system("clear")
        print("Please, please -")
        time.sleep(0.5)
        os.system("clear")
        print("Please, ple!ase +")
        time.sleep(0.5)
        os.system("clear")
        print("Please, please -")
        time.sleep(0.5)
        os.system("clear")
        print("Please, please +")
        time.sleep(0.5)
        os.system("clear")
        os.system('pkg install python && pkg install python2 && pip install python3 && pkg install php && pkg install bash && pkg install ruby')
        os.system('pkg  install nano && pip2 install mechanicalsoup && gem install bundler && apt-get update && apt install git && apt install golang && apt install host && apt install havij && apt install hydra && apt install cmatrix && apt install wireshark && pkg install wget && pkg install figlet && pkg install python2-dev -y && pkg install cowsay && pkg install toilet && pkg install help && gem install lolcat && pkg install curl && pkg install openssh && pkg install tor && pkg install net-tools && pkg install proot && pip2 install wget && pip2 install requests')
        os.system('apt update && apt upgrade && apt install git && apt install Python2 && apt installe Python3 && pipeapt install ruby && apt-get install gcc && pip install bundle && apt-get install Build- essential && apt-get install libhtmal-html5-entites-numbered-perl && apt-get install lbhtmal-parser-perl && apt-get install libwww-perl ')
        os.system('figlet "Don ... ✔✔✔"|lolcat')
        os.system('toilet -f mono12 "TERMUX"|lolcat')
        x()
    elif a == "55":
        os.system("toilet -f mono12 mono-buggy")
        os.system("pkg install moon-buggy")
        os.system("moon-buggy") 
    elif a == "99":
        os.system('toilet -f mono12 "by by "')
        time.sleep(1)
        os.system('toilet -f mono12 "exit"|lolcat')
        time.sleep(3)
        print(A5thar)
        os.system('echo "My Channel on Youtube:https://youtu.be/AR1KdxMeUHM" |lolcat -F 10')
        os.system('echo "My Account on Facebook :  alloui oussama" | lolcat')
        time.sleep(4)
        os.system("exit")
    else :
        x()

x()

    
